---
# handlers file for rsyslog_configuration

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart journald
  service:
    name: systemd-journald
    state: restarted
