---
- name: Download All the Docker images
  hosts: localhost
  vars:
      image_types:
        - base
      images_file: base-images.yml

  tasks:
    - include_vars: "{{ images_file }}"


    - debug:
        var: image_types

    - debug:
        var: registries

    - name: "Download Images {{ reg.key }}"
      with_dict: "{{ registries }}"
      loop_control:
        loop_var: reg
      include_role:
        name: docker_pull
      vars:
        registry: "{{ reg.value }}"
      when: "reg.key in image_types"
