---
- name: Download All the Docker images
  hosts: localhost
  vars:
      image_types:
        - base
      images_file: base-images.yml

  tasks:
    - include_vars: "{{ images_file }}"

    - debug:
        var: registries

    - name: "Download Images {{ item.key }}"
      with_dict: "{{ registries }}"
      include_role:
        name: docker_pull
      vars:
        registry: "{{ item.value }}"
      when: "item.key in image_types"
