#!/usr/bin/env ansible-playbook
---
- name: Push all the images into the Cluster Registry
  hosts: localhost
  vars:
      target_registry: "{{ cluster_registry | default('localhost') }}"
      import_images: True
      images_source: /opt/odie/images/
      image_manifests: "{{ lookup('fileglob', '{{images_source}}/*.yml').split(',') }}"
      #images_target: /opt/odie/config/.pushed/

  vars_files:
    - /opt/odie/src/conf/base-images.yml

  tasks:

    - name: Install docker-pycreds
      yum:
        name:
        - python-docker-py
        - python-docker-pycreds
        state: present

    - debug:
        var: item
      with_items: "{{ image_manifests }}"

    - name: Setup OCP embedded registry
      include_role:
        name: docker_login
      when: ocp_project is defined

    - name: "Loading from {{item}} manifest"
      include: tasks/push_registry.yml
      with_items: "{{ image_manifests }}"

