#!/usr/bin/env ansible-playbook
---
- name: Deploy all projects
  hosts: localhost
  roles:
    - docker_login
    - ocp_deploy
  tasks:
    - debug:
        var: projects

#    - include_role:
#        name: ocp_deploy
#      loop_control:
#        loop_var: project
#      tags:
#        - always
#      with_items:
#        - "{{ projects }}"
#
#
