#!/usr/bin/env ansible-playbook
---
- name: Configure Apache
  hosts: localhost
  connection: local
  tasks:
    - name: Install Firewalld 
      yum:
        name: firewalld
        state: present

    - name: Configure Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Configure Firewalld
      service: 
        name: firewalld
        state: started
        enabled: yes

    - name: Enable Firewall
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes


- name: Setup Directories
  hosts: localhost
  connection: local
  tasks:
    - name: Delete KS files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{kickstart_dir}}"

    - name: Create symlink
      file:
        src: "{{ kickstart_dir }}"
        path: /var/www/html/pub
        state: link
        force: yes

    - name: Delete OCP Inventory file
      file:
        path: "{{ odie_inventory_dir }}/inventory"
        state: absent

    - name: Check whether install media exists
      stat:
        path: "{{ odie_root_dir}}/install_media"
      register: install_media

    - name: Create symlink for install_media
      file:
        src: "{{ odie_root_dir}}/install_media"
        path: /var/www/html/rhel7
        state: link
        force: yes
      when: install_media.stat is defined and install_media.stat.exists and install_media.stat.isdir

- name: Install AppDev Dependencies
  hosts: localhost
  connection: local
  tasks:
    - name: Install Docker-Py
      yum:
        name: python-docker-py
        state: present

- include: playbooks/operations/setup_dnsmasq.yml
- include: playbooks/generate_configuration/generate_kickstarts.yml

