- block:
  - name: Confirm that app cert file is PEM format
    command: openssl x509 -in {{ app.path }}/{{ app.config.properties.pem_cert_file }}
    register: results
    ignore_errors: yes

  - name: Convert app cert file from DER to PEM format
    command: openssl x509 -inform der -in {{ app.path }}/{{ app.config.properties.pem_cert_file }} -out {{ app.path }}/{{ app.config.properties.pem_cert_file }}
    when: "results.rc != 0"

  - name: Convert cert to imtermediate p12 format
    command: openssl pkcs12 -export -inkey {{ app.path }}/{{ app.config.properties.pem_key_file }} -in {{ app.path }}/{{ app.config.properties.pem_cert_file }} -certfile {{ app.path }}/{{ app.config.properties.pem_cert_file }} -password pass:{{ app.config.properties.keystore_password }} -out {{ app.path }}/{{ app.config.properties.pem_cert_file }}.p12

  - name: Convert p12 to JKS format
    command: keytool -importkeystore -destkeystore {{ app.path }}/{{ app.config.properties.keystore_file }} -srckeystore {{ app.path }}/{{ app.config.properties.pem_cert_file }}.p12 -srcstoretype PKCS12 -srcalias 1 -destalias {{ app.config.properties.keystore_alias }} -srcstorepass {{ app.config.properties.keystore_password }} -deststorepass {{ app.config.properties.keystore_password }} -noprompt

  - name: Delete intermediate p12 cert
    file:
      path: "{{ app.path }}/{{ app.config.properties.pem_cert_file }}.p12"
      state: absent

  - name: Set ownership of JKS file
    file:
      path: "{{ app.path }}/{{ app.config.properties.keystore_file }}"
      state: file
      owner: admin
      group: admin
      mode: 0640

  when: app.config.properties.pem_cert_file is defined and app.config.properties.pem_key_file is defined and app.config.properties.keystore_file is defined and app.config.properties.keystore_alias is defined and app.config.properties.keystore_password is defined
  tags:
    - cert_conversion
