- name: Locate any CA certs
  find:
    paths: "{{ project.path }}/certs/CA/"
  register: found_ca_files
- block:
  - debug:
      msg: "{{ item.path }}"
    with_items: "{{ found_ca_files.files }}"

  - name: Convert trusted DER files to PEM as needed
    command: openssl x509 -inform der -in {{ item.path }} -out {{ item.path }}
    ignore_errors: yes
    with_items: "{{ found_ca_files.files }}"

  - name: Delete pre-existing CAs with matching aliases from truststore
    command: keytool -delete -destkeystore {{ project.path }}/{{ project.config.properties.truststore_file }} -deststorepass {{ project.config.properties.truststore_password }} -alias {{ item.path | basename }} -noprompt
    with_items: "{{ found_ca_files.files }}"
    ignore_errors: yes

  - name: Add trusted PEM to truststore
    command: keytool -importcert -file {{ item.path }} -destkeystore {{ project.path }}/{{ project.config.properties.truststore_file }} -deststorepass {{ project.config.properties.truststore_password }} -alias {{ item.path | basename }} -noprompt
    with_items: "{{ found_ca_files.files }}"
  when: project.config.properties.truststore_file is defined and project.config.properties.truststore_password is defined 
  tags:
    - cert_conversion
