---

  - name: Configuring PV
    include: pv_setup.yml tags=pv
    vars:
      jumphost_dir: "{{root_dir}}/{{project.name}}/pvs/{{pv}}"
    loop_control:
      loop_var: pv
    with_items:
      - "{{ project.pvs }}"

