# Ansible does not support with_subelement - https://github.com/ansible/ansible/issues/13262
# To get around this, you need to have multiple include statements
---

  - name: Setup Facts
    set_fact:
      secret_name: "{{app.name}}-postgresql-ssl-files"
      jumphost: localhost

  - debug:
      var: secret_name

  - name: Check whether Secret already exists
    command: "oc get secret/{{secret_name}} -n {{project.name}}"
    ignore_errors: yes
    register: oc_status
    delegate_to: "{{ jumphost }}"

  - name: "Delete {{secret_name}} Secret"
    command: "oc delete secret {{secret_name}}"
    ignore_errors: yes
    when: oc_status.rc == 0
    delegate_to: "{{ jumphost }}"

  - name: Creating {{secret_name}} Secret
    command: "oc secrets new {{secret_name}} server.key={{app.path}}/{{ app.config.properties.postgresql_key_file }} server.crt={{app.path}}/{{ app.config.properties.postgresql_certificate_file }} root.crt={{app.path}}/{{ app.config.properties.postgresql_ca_file }} root.crl={{app.path}}/{{ app.config.properties.postgresql_crl_file }}"
    delegate_to: "{{ jumphost }}"

  - name: Labeling {{secret_name}} Secret
    command: "oc label secret {{secret_name}} app={{app.name}} component=postgresql"
    delegate_to: "{{ jumphost }}"

  # This should succeed now
  - name: Sanity Check {{secret_name}} creation
    command: "oc get secret/{{secret_name}} -n {{project.name}}"
    delegate_to: "{{ jumphost }}"
