---

- name: "Execute Build for {{build.1.name}} on project {{item.name}}"
  command: "oc start-build {{build.1.name}} --from-dir={{build.1.path}} -n {{item.name}} --wait --follow"
  environment:
    PROJECT_PATH: "{{item.path}}/"
  loop_control:
    loop_var: build
  with_subelements:
    - "{{item.apps}}"
    - builds
