- name: "Clear {{hostname}} in /var/lib/dnsmasq/dnsmasq.leases"
  lineinfile:
    dest: /var/lib/dnsmasq/dnsmasq.leases 
    state: absent
    regexp: "{{ item }}"
  with_items:
    - "{{ hostvars[hostname].ip }}"
    - "{{ hostvars[hostname].hostname }}"
  notify: restart_dnsmasq

- name: Check /etc/dnsmasq.conf content
  shell: cat /etc/dnsmasq.conf
  register: dnsmasq_conf

- block:
  - name: Prepare DNSConfg
    copy:
      content: |-
        expand-hosts
        domain=dhcp-subnet
        dhcp-range={{ip_range_start}},{{ip_range_end}},12h
        listen-address={{gateway}}
        {% if 'jumphost' in groups and groups['jumphost'][0] is defined %}
        dhcp-host={{ mac_address }},{{hostvars[groups['jumphost'][0]].hostname}},{{hostvars[groups['jumphost'][0]].ip}},infinite
        {% endif %}
        address=/.{{default_subdomain}}/{{hostvars[groups['infra'][0]].ip}}
        bind-interfaces
      dest: /etc/dnsmasq.conf
    tags:
      - dns
    notify:
      - restart_dnsmasq
    when: '"jumphost" not in dnsmasq_conf.stdout'

  - name: "Add {{hostname}} to /etc/dnsmasq.conf"
    lineinfile:
      dest: /etc/dnsmasq.conf
      state: present
      insertafter: "{{ item.regex }}"
      line: "{{ item.line }}"
    tags:
      - dns
    with_items:
      - line: "dhcp-host={{mac_address}},{{hostvars[groups['jumphost'][0]].hostname}},{{hostvars[groups['jumphost'][0]].ip}},infinite"
        regex: "^dhcp-host"
      - line: "address=/.{{default_subdomain}}/{{hostvars[groups['infra'][0]].ip}}"
        regex: "^address"
    notify: 
      - restart_dnsmasq
    when: '"jumphost" in dnsmasq_conf.stdout and mac_address not in dnsmasq_conf.stdout'
  when: 'hostname in groups["jumphost"]'

- name: "Add {{hostname}} to /etc/hosts"
  lineinfile:
    dest: /etc/resolv.conf
    state: present
    line: "nameserver {{gateway}}"

- name: "Add {{hostname}} to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    state: absent
    regexp: "^{{hostvars[hostname].ip}}"
  notify: restart_dnsmasq

- name: "Add {{hostname}} to /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ hostvars[hostname].ip }} {{ hostname }} {{ hostname.split('.')[0]}}"
  notify: restart_dnsmasq
