- name: "Clear {{hostname}} in /var/lib/dnsmasq/dnsmasq.leases"
  lineinfile:
    dest: /var/lib/dnsmasq/dnsmasq.leases 
    state: absent
    regexp: "{{ item }}"
  with_items:
    - "{{ hostvars[hostname].ip }}"
    - "{{ hostvars[hostname].hostname }}"
  notify: restart_dnsmasq

