- name: Execute Database Test Servlet in reference App
  uri:
    url: https://{{ requestedHostPage.stdout }}/reference-app/DatabaseTestServletClient
    validate_certs: no
    return_content: yes
  register: dbPage

- name: Check response from Database test client
  fail:
  when: "'Connection worked' not in dbPage.content"
