#!/usr/bin/env ansible-playbook
---
- name: Setup DHCP / PXE Server
  hosts: localhost
  connection: local

  roles:
    - dnsmasq_configuration

- name: Setup /etc/hosts for each host
  hosts: all
  connection: local
  tasks:
  - name: Setup Jumphost for local DNS
    include_role:
      name: provision_vm
      tasks_from: add_etc_hosts_entry

