#!/usr/bin/env ansible-playbook
- name: Updating RPMs to latest from JumpHost
  hosts: all:localhost
  tasks:
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest 

    - name: Update RPMs
      command: "yum update -y"
      async: 600
      poll: 10
