---
#- name: "Check for {{output_archive}}"
#  file:
#    path: "{{output_archive}}"
#    state: absent

#- name: Copy over file
#  copy:
#    src: "{{ src_archive }}"
#    dest: "{{ output_archive }}"


- name: No local copies
  set_fact:
    output_archive: "{{ src_archive }}"

- name: Load {{ registry.name }} images into Docker
  command: docker load -i {{output_archive}}

- include: tag_push.yml
  loop_control:
    loop_var: repo
  with_items:
  - "{{ registry.repos }}"
