---
- name: Define Role Variables
  set_fact:
    output: "{{images_target}}/{{registry.name}}.tar"

- name: Define Role Variables
  set_fact:
    src_manifest: "{{images_source}}/{{registry.name}}.yml"
    output_manifest: "{{images_source}}/{{registry.name}}.yml.pushed"
    src_archive: "{{images_source}}/{{registry.name}}.tar.{{compress_ext}}"
    output_archive: "{{output}}.{{compress_ext}}"
    repos: "{{ registry.repos }}"

- name: Define Role Variables
  set_fact:
    target_registry: "{{ route_url }}"
    output_manifest: "{{images_target}}/{{registry.name}}.ocp.yml"
    output_archive: "{{images_target}}/{{registry.name}}.ocp.tar.{{compress_ext}}"
  when: ocp_project is defined

- name: Copy Manifest
  copy:
    src: "{{src_manifest}}"
    dest: "{{output_manifest}}"
  register: manifest

- name: "Load Archive {{src_manifest}}"
  block:
    - name: Load image
      include: load_archive.yml
  rescue:
    - name: Delete old manifest
      file:
        path: "{{output_manifest}}"
        state: absent

    - fail:
        msg: "Unable to load {{src_manifest}}"

  when: manifest.changed == true
