# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
#alias tailodie='tail -f "/tmp/\$(ls -1tr /tmp | grep odie | tail -1)"'
#alias toodie='cd /opt/odie'

# Source global definitions
if [ -f /etc/bashrc  ]; then
    . /etc/bashrc
fi

export ANSIBLE_CONFIG=/opt/odie/src/ansible.cfg
