apiVersion: v1
kind: Template
labels:
  release: v1
  template: odie-bc-binary
metadata:
  name: odie-bc-binary
  annotations:
    description: 'odie Binary Build w/ Dockerfile'
    iconClass: icon-shadowman
    tags: org,client,odie
    version: 1.0.0
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}
    annotations:
      description: 'Binary build of the ${APPLICATION_NAME} image'
    labels:
      app: ${APPLICATION_NAME}
  spec:
    triggers:
      - type: ConfigChange
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: '${APPLICATION_NAME}:latest'
    source:
      type: Binary
      binary:
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          namespace: 'openshift'
          name: '${IMAGE_NAME}'
    resources:
    postCommit:
parameters:
- description: App Name
  name: APPLICATION_NAME
  required: true
- description: EAP Image Name
  name: IMAGE_NAME
  required: true
