apiVersion: v1
kind: Template
labels:
  release: v1
  template: odie-eap-keystore-secret
metadata:
  name: 'odie-eap-keystore-secret'
  anotations:
    description: 'odie eap keystore secret'
    iconClass: 'icon-shadowman'
    tags: org,client,odie
    version: v1
objects:
- apiVersion: v1
  kind: Secret
  labels:
    app: ${APPLICATION_NAME}
  metadata:
    name: ${APPLICATION_NAME}-eap-keystore-strings
    selfLink: /api/v1/namespaces/secrets/${APPLICATION_NAME}-eap-keystore-strings
  stringData:
    KEYSTORE_ALIAS: '${KEYSTORE_ALIAS}'
    KEYSTORE_PASSWORD: '${KEYSTORE_PASSWORD}'
parameters:
- name: APPLICATION_NAME
  description: 'The name of this application'
  required: true
- name: KEYSTORE_ALIAS
  description: 'The alias for the key in the keystore passed in via KEYSTORE_FILE.'
  required: true
- name: KEYSTORE_PASSWORD
  description: 'The password for the keystore passed in via KEYSTORE_FILE.'
  required: true
