apiVersion: v1
kind: Template
labels:
  release: v1
  template: odie-public-routes
metadata:
  name: 'odie-routes'
  anotations:
    description: 'odie Routes'
    iconClass: 'icon-shadowman'
    tags: org,client,odie
    version: v1
objects:
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPLICATION_NAME}-services-${ROUTE_SET_NAME}"
    annotations:
      description: 'Route for odie HTTP/UI services.'
    labels:
      public_facing: 'false'
      app: ${APPLICATION_NAME}
  spec:
    host: ${HOST}
    to:
      kind: Service
      name: ${APPLICATION_NAME}-services-https
      weight: 100
    tls:
      termination: passthrough
      insecureEdgeTerminationPolicy: Redirect
parameters:
- name: APPLICATION_NAME
  description: 'The name of this application'
  required: true
- name: HOST
  description: 'The host the traffic will be coming through.'
- name: ROUTE_SET_NAME
  description: 'The name for this set of routes. EX: internal, external, public.'
  required: true
