apiVersion: v1
kind: Template
labels:
  release: v1
  template: odie-truststore-password-secret
metadata:
  name: 'odie-truststore-password-secret'
  anotations:
    description: 'odie truststore password secret'
    iconClass: 'icon-shadowman'
    tags: org,client,odie
    version: v1
objects:
- apiVersion: v1
  kind: Secret
  labels:
    app: ${PROJECT_NAME}
  metadata:
    name: ${PROJECT_NAME}-truststore-password
    selfLink: /api/v1/namespaces/secrets/${PROJECT_NAME}-truststore-password
  stringData:
    TRUSTSTORE_PASSWORD: '${TRUSTSTORE_PASSWORD}'
parameters:
- name: PROJECT_NAME
  description: 'The name of the project'
  required: true
- name: TRUSTSTORE_PASSWORD
  description: 'The password for the keystore passed in via TRUSTSTORE_FILE.'
  required: true
