---
# This playbook prepares the OCP hosts for the installer and ensures all
# of the prerequisites are ready.

- name: Configure SSH Keys
  hosts: all:localhost
  vars:
    jumphost_gpg_key: /etc/pki/rpm-gpg/RPM-GPG-KEY-odie-build-server

  tasks:

    - name: Copy jumphost public GPG key to host
      copy:
        dest: "{{ jumphost_gpg_key }}"
        src: "{{ jumphost_gpg_key }}"

    - name: Import GPG keys
      command: "rpm --import {{ item }}"
      with_items:
        - "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        - "{{ jumphost_gpg_key }}"

    - name: Ensure yum imports gpg key
      command: "yum -y repolist"

