#!/usr/bin/env ansible-playbook
---
- name: Setup rsyslog
  hosts: all

  roles:
    - rsyslog_configuration

- name: Restart docker registry
  hosts: localhost

  tasks:
    - name: Stop docker-distribution services
      systemd:
        name: docker-distribution
        state: stopped

    - name: Start and enable docker-distribution services
      systemd:
        name: docker-distribution
        state: started
        enabled: yes

