- name: Set Application Fact
  set_fact:
    app: "{{ lookup('env', 'ODIE_SELECTED_APPLICATION') }}"
  tags:
    - always

- name: Scale down the Application and PostgreSQL pods
  include: scale_down_app.yml
  tags:
    - app
  vars:
    project: "{{item[0]}}"
    app: "{{item[1]}}"
  with_subelements:
    - "{{ projects }}"
    - apps

- name: Provision Application Metadata
  include: undeploy_apps.yml
  tags:
    - app
  vars:
    project: "{{item[0]}}"
    app: "{{item[1]}}"
  with_subelements:
    - "{{ projects }}"
    - apps

- name: Scale down the Broker
  include: scale_down_project.yml
  when: app == ""
  loop_control:
    loop_var: project
  tags:
    - project
  with_items:
    - "{{ projects }}"

- name: Undeploy Project
  include: undeploy_project.yml
  when: app == ""
  loop_control:
    loop_var: project
  tags:
    - project
  with_items:
    - "{{ projects }}"

- include: ocp_pv_removal.yml tags=pv_undeploy
  tags:
    - pv
  vars:
    project: "{{item[0]}}"
    app: "{{item[1]}}"
  with_subelements:
    - "{{ projects }}"
    - apps


- include: project_pv_removal.yml tags=pv_undeploy
  tags:
    - pv
  loop_control:
    loop_var: project
  when: app == ""
  with_items:
    - "{{ projects }}"
