# Ansible does not support with_subelement - https://github.com/ansible/ansible/issues/13262
# To get around this, you need to have multiple include statements
---
  - debug:
      var: groups['lb'][0]

  - name: Setup Facts
    set_fact:
      pv_name: "pv-{{project.name}}-{{pv}}"
      templates_dir: "/opt/odie/ocp_templates"
      jumphost: localhost

  - name: Setup Facts
    set_fact:
      nfs_hostname: "{{groups['lb'][0]}}"
      nfs_directory: "/ocp/pvs/{{pv_name}}"
      nfs_mount_state: unmounted
      pv_yaml: "{{templates_dir}}/{{pv_name}}.yml"

  - name: Delete template YAML directory
    file:
      path: "{{ pv_yaml }}"
      state: absent
    delegate_to: "{{ jumphost }}"

  - name: Check whether PV already exists
    command: "oc get pv/{{pv_name}} -n {{project.name}}"
    ignore_errors: yes
    register: oc_status
    delegate_to: "{{ jumphost }}"

  - name: Deleting {{pv_name}} PV
    command: "oc delete pv/{{pv_name}} -n {{project.name}}"
    when: oc_status.rc == 0
    delegate_to: "{{ jumphost }}"

  - name: Unmount {{ jumphost_dir }}
    shell: "umount -f {{jumphost_dir}} || /bin/true"
    delegate_to: "{{jumphost}}"

  - name: Remove {{ jumphost_dir }} /etc/fstab entry
    lineinfile:
      dest: /etc/fstab
      regexp: "^{{nfs_hostname}}:{{nfs_directory}}"
      state: absent 
    delegate_to: "{{jumphost}}"

  - name: NFS Directory Removal
    file:
      path: "{{ nfs_directory }}"
      state: absent
    delegate_to: "{{nfs_hostname}}"

