- name: Overwrite default app_shutdown_timeout
  set_fact: app_shutdown_timeout="{{ project.config.properties.app_shutdown_timeout }}"
  when: project.config.properties.app_shutdown_timeout is defined

- name: Check if broker-amq exists and has replicas
  command: "oc get deploymentconfig broker-amq -n {{ project.name }} -o jsonpath='{.items[*].status.replicas}'"
  ignore_errors: true
  register: broker_oc_get_output

- block:
  - name: Scale down application  DC
    command: "oc scale deploymentconfig broker-amq -n {{ project.name }} --replicas=0"
    ignore_errors: true

  - name: Check if the application DC has hit a replica count of 0
    shell: " oc get deploymentconfig broker-amq -n {{ project.name }} --template='{{ '{{' }} .status.replicas {{ '}}' }}'"
    register: broker_replica_count
    until: broker_replica_count.stdout == "0"
    retries: "{{ ( app_shutdown_timeout | int / 5 ) | round(0, 'ceil') | int }}"
    ignore_errors: true
    delay: 5
  when:
    - broker_oc_get_output.stderr == ""
    - broker_oc_get_output.stdout|int > 0

