
- name: Check whether {{project.name}} exists
  command: "oc get project {{project.name}}"
  ignore_errors: true
  register: oc_project

- name: "Watching for completion of project removal"
  command: "{{odie_src_dir}}/scripts/delete-project.sh {{project.name}}"
  when: oc_project.rc == 0

- name: Marker File
  set_fact:
    marker_file: "{{project.path}}/.odie-project-provision"

- name: Delete Marker file
  file:
    path: "{{marker_file}}"
    state: absent
