- name: "Check whether {{project.name}} exists"
  command: "oc get dc {{app.name}} -n {{project.name}}"
  ignore_errors: true
  register: oc_dc

- name: Marker File
  set_fact:
    marker_file: "{{app.path}}/.odie-app-provision"

- name: "Delete all application components {{app.name}}"
  command: "oc delete all -l app={{app.name}} -n {{project.name}}"
  when: oc_dc.rc == 0

- name: "Delete application cronjob components {{app.name}}"
  command: "oc delete cronjob -l app={{app.name}} -n {{project.name}}"
  when: oc_dc.rc == 0

- name: "Undeploy PVCs {{app.name}}"
  command: "oc delete pvc -l app={{app.name}} -n {{project.name}}"
  when: oc_dc.rc == 0

- name: "Undeploy Secrets {{app.name}}"
  command: "oc delete secret -l app={{app.name}} -n {{project.name}}"
  when: oc_dc.rc == 0

- name: "Undeploy Service Accounts {{app.name}}"
  command: "oc delete sa -l app={{app.name}} -n {{project.name}}"
  when: oc_dc.rc == 0

- name: Delete Marker file
  file:
    path: "{{marker_file}}"
    state: absent
  when: oc_dc.rc == 0
