- name: Shut down EAP Pods
  shell: "oc get dc -o name | grep app | grep -v postgres | xargs oc scale --replicas=0 --timeout=5m"
  register: shutdown_all_eap

- name: Shut down PostgreSQL Pods
  shell: "oc get dc -o name | grep postgres | xargs oc scale --replicas=0 --timeout=5m"
  register: shutdown_all_postgres

- name: Shut down AMQ Pods
  shell: "oc get dc -o name | grep amq | xargs oc scale --replicas=0 --timeout=5m"
  register: shutdown_all_amq
