
- name: Shutdown all running pods
  include: controlled_shutdown.yml
  tags:
    - shutdown
  loop_control:
    loop_var: project
  with_items:
    - "{{ projects }}"

- name: Configuring Application Secrets
  include_role:
    name: ocp_deploy
    tasks_from: secret_setup.yml
  vars:
    project: "{{item[0]}}"
    app: "{{item[1]}}"
  with_subelements:
    - "{{ projects }}"
    - apps
  tags:
    - secrets

- name: Startup all applications
  include: controlled_startup.yml
  tags:
    - startup
